/**
 * Competitor Return Parser — extracts personal info, dependents, and financial
 * summary from a completed IRS Form 1040 PDF generated by competitor tax software.
 *
 * Two extraction strategies (tried in order):
 * 1. AcroForm fields — works on IRS fillable PDFs (rare from competitors)
 * 2. Text-based heuristics — primary path for flat (non-fillable) competitor PDFs
 *
 * All processing runs client-side. Data never leaves the browser.
 * Full SSNs are immediately truncated to last 4 — never stored in state.
 */
import './pdfWorkerInit';
import { FilingStatus } from '@nimbus/engine';
export type Confidence = 'high' | 'medium' | 'low';
export interface ExtractedField<T> {
    value: T;
    confidence: Confidence;
}
export interface ExtractedDependent {
    firstName: string;
    lastName: string;
    ssnLastFour?: string;
    relationship?: string;
}
export interface CompetitorExtractResult {
    personalInfo: {
        firstName: ExtractedField<string>;
        lastName: ExtractedField<string>;
        addressStreet: ExtractedField<string>;
        addressCity: ExtractedField<string>;
        addressState: ExtractedField<string>;
        addressZip: ExtractedField<string>;
        filingStatus: ExtractedField<FilingStatus | null>;
        spouseFirstName?: ExtractedField<string>;
        spouseLastName?: ExtractedField<string>;
    };
    dependents: ExtractedDependent[];
    financials: Record<string, number>;
    detectedProvider?: string;
    detectedTaxYear: number;
    warnings: string[];
}
export declare function parseCompetitorReturn(file: File): Promise<CompetitorExtractResult>;
/**
 * Sanitize an SSN string to only the last 4 digits.
 * SECURITY: Full SSNs are never stored — only last 4 are retained.
 */
export declare function sanitizeSsnToLastFour(raw: string): string | undefined;
